# Generated by Django 6.0.7 on 2026-08-03 03:47

# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix_name", models.CharField(max_length=10, choices=[("1", "นาย"), ("2", "นาง"), ("3", "นางสาว")], default=1)),
                ("stu_id", models.CharField(max_length=10, unique=True)),
                ("fname", models.CharField(max_length=50, blank=True)),
                ("lname", models.CharField(max_length=50, blank=True)),
            ],
        ),
    ]
