# Generated by Django 6.0.7 on 2026-08-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.major",
            ),
        ),
    ]
