# Generated by Django 6.0.6 on 2026-08-31 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_student_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อหมวดหมู่วิชา"
                    ),
                ),
            ],
            options={
                "verbose_name": "หมวดหมู่วิชา",
                "verbose_name_plural": "หมวดหมู่วิชา",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(max_length=20, unique=True, verbose_name="รหัสวิชา"),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=150, verbose_name="ชื่อรายวิชา"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="my_app.category",
                        verbose_name="หมวดหมู่วิชา",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายวิชา",
                "verbose_name_plural": "รายวิชา",
                "ordering": ["subject_code"],
            },
        ),
    ]
