# Generated by Django 6.0.6 on 2026-08-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_category_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollements",
                        to="my_app.student",
                        verbose_name="นักศึกษา",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollements",
                        to="my_app.subject",
                        verbose_name="รายวิชา",
                    ),
                ),
            ],
        ),
    ]
