# Generated by Django 6.0.6 on 2026-08-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_category_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrolls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1/2569", "1/2569"),
                            ("2/2569", "2/2569"),
                            ("3/2569", "3/2569"),
                        ],
                        default="1/2569",
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolls",
                        to="my_app.student",
                        verbose_name="นักศึกษา",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolls",
                        to="my_app.subject",
                        verbose_name="รายวิชา",
                    ),
                ),
            ],
        ),
    ]
