# Generated by Django 6.0.6 on 2026-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_enrolls"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrolls",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "semester"),
                name="unique_student_subject_semester",
            ),
        ),
    ]
